### ISSUE TITLE
todo list for v1 of workshop

### ISSUE THREAD

**Issue by maxogden** [maxogden/get-dat#8]
- [x] hosting infrastructure (@mafintosh)
- [x] docker inside docker (bundling needed images etc) (@mafintosh)
- [x] finish markdown content (@maxogden)
- [x] come up with a data processing use case
- [x] create a gasket pipeline for [brunos pipeline](https://gist.github.com/bmpvieira/e40835676c086d3f92c4) (@bmpvieira)
- [x] docker image with samtools in it so we can use `samtools tview` to view the reads (@pkafei)
- [x] in browser workshop ui (@mafintosh, @maxogden)

**Comment by syzer** [comment]
its awesome!

**Comment by rukku** [comment]
That geospatial example looks great. :smile:  Will it be part of the tutorial soon?
